name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Install goreleaser
        run: |
          wget https://github.com/goreleaser/goreleaser/releases/download/v0.182.1/goreleaser_Linux_x86_64.tar.gz
          tar -xvf goreleaser_Linux_x86_64.tar.gz
          sudo mv goreleaser /usr/local/bin/
      - name: Check if there are any tags
        id: check_tags
        run: |
          echo ::set-output name=tag::$(git tag --points-at HEAD)
      - name: Create initial tag
        if: steps.check_tags.outputs.tag == ''
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git tag v0.1.0
          git push origin v0.1.0
      - name: Run goreleaser
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          goreleaser release --rm-dist --skip-publish